joint_names:
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6

maximum_velocities:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5

maximum_accelerations:
  - 1.0
  - 0.5
  - 0.4
  - 1.0
  - 10.0
  - 10.0
