# =========================
# ROBOT r1
# =========================
/r1/controller_manager:
  ros__parameters:
    enable_introspection: true
    enable_statistics: true
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    effort_controller:
      type: effort_controllers/JointGroupEffortController


/r1/position_controller:
  ros__parameters:
    joints:
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
    interface_name: position


/r1/velocity_controller:
  ros__parameters:
    joints:
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
    interface_name: velocity


/r1/effort_controller:
  ros__parameters:
    joints:
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
    interface_name: effort


# =========================
# ROBOT r2
# =========================
/r2/controller_manager:
  ros__parameters:
    enable_introspection: true
    enable_statistics: true
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    effort_controller:
      type: effort_controllers/JointGroupEffortController


/r2/position_controller:
  ros__parameters:
    joints:
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
    interface_name: position


/r2/velocity_controller:
  ros__parameters:
    joints:
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
    interface_name: velocity


/r2/effort_controller:
  ros__parameters:
    joints:
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
    interface_name: effort
